apiVersion: apps/v1
kind: Deployment
metadata:
  name : python-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
        labels:
            app: python-app
    spec:
      containers:
      - name: app
        image: manish3097/python-app
        env:
            - name: REDIS_PASSWORD
              valueFrom:
                     secretKeyRef:
                          name: redis
                          key: REDIS_PASSWORD
        resources:
          requests:
                memory: "64Mi"
                cpu: "250m"
          limits:
                memory: "128Mi"
                cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
            - configMapRef:
                    name: env
        
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: python-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort
 