apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-app
spec:
  maxReplicas: 6
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-app
  targetCPUUtilizationPercentage: 60