name: CI-CD

on:
    push:
        branches: 
            - main


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout source code.
                uses: actions/checkout@v3
            -
                name: Install python dependencies
                run: pip install -r requirements.txt
              
            -
                name: Run Unit tests
                run: python ./tests/test.py

