name: CI-CD

on:
  push:
    branches: ["master"]


jobs:
    Run-tests:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout source code.
                uses: actions/checkout@v3
            -
                name: Install python dependencies
                run: pip install -r requirements.txt
              
            -
                name: Run Unit tests
                run: python ./tests/test.py
    docker-build:
        runs-on: [self-hosted, linux]
        steps:
            -   name: checkout source code.
                run: docker build . -t python-app
