name: CI-CD

on:
  push:
    branches: ["feature"]


jobs:
    Run-tests:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout source code.
                uses: actions/checkout@v3
            -
                name: Install python dependencies
                run: pip install -r requirements.txt
              
            -
                name: Run Unit tests
                run: python ./tests/test.py
    docker-build:
        runs-on: [self-hosted, linux]
        needs: ['Run-tests']       
        steps:
            -   
                name: checkout source code.
                uses: actions/checkout@v3 

            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}            -   
            -
                name: Build docker image
                run:  sh ./scripts/dockerBuild.sh
                env:
                            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
                            BUILD_NUMBER: $env:GITHUB_RUN_NUMBER
            
  
                  