name: Pull request pipeline

 
on: [ pull_request]
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   
                name: checkout source code.
                uses: actions/checkout@v3
            -
                name: Install python dependencies
                run: pip install -r requirements.txt
              
            -
                name: Run Unit tests
                run: python ./tests/test.py
    docker-build:
        runs-on: [self-hosted, linux]
        needs: ['build']       
        steps:
            -   
                name: checkout source code.
                uses: actions/checkout@v3 
            -   
                name: Build docker image
                run: sudo docker build . -t python-app